import Head from "next/head";
import Link from "next/link";

import { RouterOutputs, api } from "@/utils/api";
import {
  SignInButton,
  SignOutButton,
  UserButton,
  useUser,
} from "@clerk/nextjs";
import { NextPage } from "next";

function CreatePostWizard() {
  const { user } = useUser();

  console.log(user);

  if (!user) return null;

  return (
    <div className="flex w-full gap-3">
      <img
        src={user.imageUrl}
        alt="Profile image"
        className="h-14 w-14 rounded-full"
      />
      <input
        placeholder="Type something..."
        className="grow bg-transparent outline-none"
      />
    </div>
  );
}

type PostWithUser = RouterOutputs["posts"]["getAll"][number];

function PostView(props: PostWithUser) {
  const { post, author } = props;
  return (
    <article key={post.id} className="flex gap-4 border-b border-slate-400 p-4">
        <img
          src={author.profilePicture}
          alt="Picture"
          className="h-14 w-14 rounded-full"
        />
      <div className="flex flex-col items-center gap-3">
        <p className="flex text-slate-300">
        {`@${author.username}`}
        </p>
        <p>{post.content}</p>
      </div>
    </article>
  );
}

export default function Home() {
  const user = useUser();

  const { data, isLoading } = api.posts.getAll.useQuery();

  if (isLoading) return <p>Loading...</p>;

  if (!data) return <p>Something went wrong</p>;

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex h-screen justify-center">
        <div className="h-full w-full border-x border-slate-400 md:max-w-2xl">
          <div className="flex border-b border-slate-400 p-4">
            {!user.isSignedIn && (
              <div className="flex justify-center">
                <SignInButton />
              </div>
            )}
            {user.isSignedIn && <CreatePostWizard />}
          </div>
          <div>
            {[...data, ...data]?.map((fullPost) => (
              <PostView {...fullPost} key={fullPost.post.id} />
            ))}
          </div>
        </div>
      </main>
    </>
  );
}
